// src/icons/foodIcons.js
import {
    FaCoffee,
    FaMugHot,
    FaGlassWhiskey,
    FaCheese,
    FaEgg,
    FaBreadSlice,
    FaAppleAlt,
    FaLemon,
    FaIceCream,
    FaWineGlass,
    FaCookie,
    FaUtensils,
    FaHamburger,
    FaPizzaSlice,
    FaCarrot,
    FaFish,
    FaCocktail,
    FaQuestion,
  } from "react-icons/fa";
  
  import {
    MdLocalCafe,
    MdLocalBar,
    MdRestaurantMenu,
    MdFastfood,
    MdCake,
    MdEgg,
    MdFreeBreakfast,
  } from "react-icons/md";
  
  import {
    GiCoffeeCup,
    GiCheeseWedge,
    GiSandwich,
    GiFruitBowl,
    GiCroissant,
    GiKnifeFork,
    GiSteak,
    GiCupcake,
    GiFruitTree,
    GiWineBottle,
    GiWineGlass,
  } from "react-icons/gi";
  
  import {
    IoIosBeer,
    IoIosWine,
    IoIosPizza,
    IoIosIceCream,
    IoMdCafe,
    IoMdRestaurant,
  } from "react-icons/io";
  
  export const foodIcons = {
    FaCoffee,
    FaMugHot,
    FaGlassWhiskey,
    FaCheese,
    FaEgg,
    FaBreadSlice,
    FaAppleAlt,
    FaLemon,
    FaIceCream,
    FaWineGlass,
    FaCookie,
    FaUtensils,
    FaHamburger,
    FaPizzaSlice,
    FaCarrot,
    FaFish,
    FaCocktail,
    MdLocalCafe,
    MdLocalBar,
    MdRestaurantMenu,
    MdFastfood,
    MdCake,
    MdEgg,
    MdFreeBreakfast,
    GiCoffeeCup,
    GiCheeseWedge,
    GiSandwich,
    GiFruitBowl,
    GiCroissant,
    GiKnifeFork,
    GiSteak,
    GiCupcake,
    GiFruitTree,
    GiWineBottle,
    GiWineGlass,
    IoIosBeer,
    IoIosWine,
    IoIosPizza,
    IoIosIceCream,
    IoMdCafe,
    IoMdRestaurant,
    FaQuestion, // fallback
  };
  